### ISSUE TITLE
typo: Continous Deliey

### ISSUE THREAD

**Issue by mertssmnoglu** [burakkrt/CI-CD-Notion#1]
Burak merhabalar. Bir süredir not aldığın yazılarını takip ediyorum. sanırsam notion üzerinde yazıp ardından html/md dönüşümlerini yapıyorsun. 14. Satırdaki başlığı `Continous Delivery` olarak düzeltmen ilk defa görmüş birisinin kafasının karışmaması adına güzel olacaktır.  
https://github.com/burakkrt/CI-CD-Notion/blob/489c93558d31a7e5271573623cd422703f1c7797/README.md?plain=1#L14
Kolay gelsin.

**Comment by burakkrt** [comment]
Merhaba Mert.

Öncelikle dikkatli takibin ve geri bildirim için teşekkür ederim. Notlarımın takip edilip geri bildirimde bulunulması beni inanılmaz mutlu etti. Bu yazım yanlışını gözden kaçırmış olmalıyım çünkü aynı anda birden fazla işle uğraşıyordum.

Geri bildirim doğrultusunda ilgili alanda düzenleme gerçekleştirdim. Contributor olduğun için teşekkür ederim. İyi günler. @mertssmnoglu

**Comment by mertssmnoglu** [comment]
Rica ederim ne demek.
İyi günler.
